### ISSUE TITLE
Latest version doesn't work - seems outdated

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [samerton/Nameless-VotingPlugin#12]
I just got an alert on NamelessMC's StaffCP that "check if directory is writable... modules/VotingPlugin", etc

and when i go here
![image](https://user-images.githubusercontent.com/56804505/116784864-c1e8ae00-aa96-11eb-8dd2-0506e3616750.png)

i get this
![image](https://user-images.githubusercontent.com/56804505/116784869-cf9e3380-aa96-11eb-8b20-519cc555687a.png)

everything is blank

**Comment by samerton** [comment]
Hi,

Yes, the module doesn't officially support anything later than pre-release 7. There's no ETA on an update yet

**Comment by samerton** [comment]
I've just released a module update which supports Nameless v2 pre-release 10
