### ISSUE TITLE
Unable to recieve data | Question

### ISSUE THREAD

**Issue by PadowYT2** [samerton/Nameless-VotingPlugin#15]
I have the same problem as #14 , I have a question about it, do you need the actual plugin, I'm just making it for a template

**Comment by samerton** [comment]
Hi,

You need a valid database table generated by the plugin to get past the "Unable to receive data" message

If you are not able to install the plugin, somebody may be able to send you a dump of their database table for you to import

**Comment by PadowYT2** [comment]
nvm, got fixed, but thx
