### ISSUE TITLE
Update to pr13

### ISSUE THREAD

**Issue by BlueTree242** [samerton/Nameless-VotingPlugin#16]
The title says it all, please update the module to pr13, this module wasn't updated in a while

**Comment by Creeperz653** [comment]
Blue the blue tree being in blue mess

**Comment by Creeperz653** [comment]
@samerton

**Comment by joshwenke** [comment]
I would love to see this plugin updated to 2.1.0. @samerton is this possible?

**Comment by samerton** [comment]
Long overdue but finally updated!
