### ISSUE TITLE
[Suggestion] Add LastMonthTop Display + Sorting type

### ISSUE THREAD

**Issue by ILikeOrangeJuice** [samerton/Nameless-VotingPlugin#19]
As requested I post this here as an issue :).

I'd love to have another row, Last Month Top, added to the current ones and it also being added as an sorting option. It's nice to display the last months highest voters, esp. when you give rewards based on it like our network does! 

Here is also a simple visual explanation in case I am bad at explaining haha.

Currently it is like this:
Daily | Weekly | Monthly | All Time

How I would love it to be:
Daily | Weekly | Monthly | Last Month Top | All Time

+ Sorting option of the Last Month Top

------

Thanks for your time and efforts!

**Comment by samerton** [comment]
https://github.com/samerton/Nameless-VotingPlugin/commit/f99a72813a79139ee5928b4d9e7dc82b5bd7f68c

Available in 1.0.5

Thanks for the suggestion!
